# Generated by Django 6.0.7 on 2026-07-12 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_platformuser_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('type', models.CharField(max_length=50)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='driver',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='driver',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_drivers_set', to='fleet.vehicle'),
        ),
        migrations.AddField(
            model_name='driver',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='driver',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_category',
            field=models.CharField(default='Class A CDL', max_length=30),
        ),
        migrations.AddField(
            model_name='driver',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='photo',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='driver',
            name='safety_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='expense',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fuel_logs', to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='fuel_type',
            field=models.CharField(default='Diesel', max_length=40),
        ),
        migrations.AddField(
            model_name='fuellog',
            name='odometer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='technician',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='type',
            field=models.CharField(default='Routine', max_length=40),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='workshop',
            field=models.CharField(default='Internal Workshop', max_length=120),
        ),
        migrations.AddField(
            model_name='trip',
            name='arrival_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='cargo_weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='trip',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trip',
            name='planned_distance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trip',
            name='remarks',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='assigned_driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_vehicles_set', to='fleet.driver'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='average_mileage',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='depot',
            field=models.CharField(default='Main Garage', max_length=120),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fitness_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_capacity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(default='Diesel', max_length=30),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='max_load',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='name',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vehicle',
            name='odometer',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pollution_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='purchase_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='remarks',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(default='AVAILABLE', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='status',
            field=models.CharField(default='SCHEDULED', max_length=20),
        ),
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(default='DRAFT', max_length=20),
        ),
    ]
